#!/bin/bash


echo "RUNNING DUCKLAKE PIPELINE"
echo "BUILD PACKAGE & SYNC CURRENT DISTRIBUTION DEPENDENCIES"

uv sync
echo "DEPENDENCIES RESOLVED"

cd ./src
echo "CURRENT WORKING DIR: PROJECT SOURCE"

uv run etl/ingestion/main.py
echo "DATA PIPELINE REFRESHED"

echo "BEGIN DBT RUN"

scripts/run_dbt.sh