
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'test_dbt_ducklake'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'main_duckdb'

flags:
  send_anonymous_usage_stats: false


models:
  test_dbt_ducklake:
    transformation:
      schema: main
    reverse_etl:
      database: postgres_db
      schema: public