main_duckdb:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: data/test_meta_db.duckdb
      extensions:
        - spatial
        - httpfs
        - parquet
        - postgres
      threads: 2

    prod:
      type: postgres
      host: "{{ env_var('RDS_HOST') }}"
      user: "{{ env_var('RDS_USER') }}"
      password: "{{ env_var('RDS_PASSWORD') }}"
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: lakehouse
