mainduck:

  target: dev
  outputs:
    dev:
      type: duckdb
      extensions:
        - spatial
        - httpfs
        - parquet
        - postgres
        - ducklake
      settings:
        s3_region: eu-central-1
        s3_access_key_id: "{{ env_var('S3_KEY') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET') }}"
      secrets:
        - type: postgres
          name: 'postgres_sec'
          host: '{{ env_var("RDS_HOST") }}'
          port: 5432
          database: '{{ env_var("RDS_DB") }}'
          user: '{{ env_var("RDS_USER") }}'
          password: '{{ env_var("RDS_PASSWORD") }}'
        - type: ducklake
          name: 'lakehouse'
          metadata_path: ''
          data_path: '{{ env_var("S3_PATH") }}'
          metadata_parameters: 
            type: postgres  
            secret: postgres_sec
      threads: 2
      attach:
        - path: "ducklake:lakehouse"
          options:
            OVERRIDE_DATA_PATH: true
          alias: remote_lake


    # prod:
    #   type: postgres
    #   host: "{{ env_var('RDS_HOST') }}"
    #   user: "{{ env_var('RDS_USER') }}"
    #   password: "{{ env_var('RDS_PASSWORD') }}"
    #   port: 5432
    #   dbname: postgres # or database instead of dbname
    #   schema: lakehouse
